### ISSUE TITLE
[BUG] - Transmat Terminal bind locks character movement

### ISSUE THREAD

**Issue by Zasig** [NexusForever/NexusForever#291] opened 2020-06-11 12:42 UTC
Date: 11.06.2020

Description: Tried binding my character to the transmat terminal in FCON Headquarters. After binding character cannot move anymore, jumping and dashing is still possible.

Occurrence: always

OS: Windows 10 - 1909

Branch/Commit: Kirmmin's Test Server

STR: 
1. create Character
2. go to any Transmat Terminal and bind it.

Observed: After binding, character cannot walk/run anymore

Expected: Binding Transmat Terminal and be able to continue walking/running

**Comment by Matt-Hurd** [comment] 2021-12-02 03:12
Duplicate of #253

**Closed as completed by Matt-Hurd** 2021-12-02 03:12 UTC
